-- Create ballots table for vote storage
CREATE TABLE IF NOT EXISTS public.ballots (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sr_numbers JSONB NOT NULL,
  entered_by VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable Row Level Security (for simple app)
ALTER TABLE public.ballots DISABLE ROW LEVEL SECURITY;

-- Create index on created_at for faster lookups
CREATE INDEX IF NOT EXISTS idx_ballots_created_at ON public.ballots(created_at);
