const express = require('express');
const cors = require('cors');
const multer = require('multer');
const XLSX = require('xlsx');
const fs = require('fs');
require('dotenv').config();

const { createClient } = require('@supabase/supabase-js');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static('public'));
app.use('/uploads', express.static('uploads'));

const supabaseUrl = process.env.SUPABASE_URL || (process.env.SUPABASE_PROJECT_ID ? `https://${process.env.SUPABASE_PROJECT_ID}.supabase.co` : null);
const supabaseKey = process.env.SUPABASE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('SUPABASE_URL or SUPABASE_PROJECT_ID and SUPABASE_KEY (or SUPABASE_SERVICE_ROLE_KEY) are required.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const upload = multer({ dest: 'uploads/' });

const DEFAULT_USERNAME = 'NEST';
const DEFAULT_PASSWORD = 'sardar123';

// Simple JSON file-based role store (no DB schema change needed)
const ROLES_FILE = './user_roles.json';
function loadRoles() {
  try { return JSON.parse(fs.readFileSync(ROLES_FILE, 'utf8')); } catch { return {}; }
}
function saveRoles(roles) {
  fs.writeFileSync(ROLES_FILE, JSON.stringify(roles, null, 2));
}
function getUserRole(username) {
  return loadRoles()[username] || 'dashboard';
}
function setUserRole(username, role) {
  const roles = loadRoles();
  roles[username] = role || 'dashboard';
  saveRoles(roles);
}
function deleteUserRole(username) {
  const roles = loadRoles();
  delete roles[username];
  saveRoles(roles);
}
// Ensure default admin has admin role
setUserRole(DEFAULT_USERNAME, 'admin');

// Simple JSON file-based ballot entry log (tracks who entered each ballot)
const BALLOT_LOG_FILE = './ballot_entry_log.json';
function loadBallotLog() {
  try { return JSON.parse(fs.readFileSync(BALLOT_LOG_FILE, 'utf8')); } catch { return {}; }
}
function saveBallotLog(log) {
  fs.writeFileSync(BALLOT_LOG_FILE, JSON.stringify(log, null, 2));
}
function setBallotEntry(ballotId, enteredBy) {
  const log = loadBallotLog();
  log[String(ballotId)] = { entered_by: enteredBy, timestamp: new Date().toISOString() };
  saveBallotLog(log);
}
function getBallotEntry(ballotId) {
  return loadBallotLog()[String(ballotId)] || null;
}
function removeBallotEntry(ballotId) {
  const log = loadBallotLog();
  delete log[String(ballotId)];
  saveBallotLog(log);
}

// Initialize users and ballots tables
async function initializeDatabase() {
  try {
    console.log('🔄 Initializing database tables...');
    
    // Initialize Users table
    const { error: usersError } = await supabase.rpc('exec', {
      sql: `
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          username VARCHAR(255) UNIQUE NOT NULL,
          password VARCHAR(255) NOT NULL,
          role VARCHAR(50) DEFAULT 'dashboard',
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        -- Ensure RLS is disabled for the simple registration flow
        ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
      `
    });
    if (usersError) console.error('❌ Error creating users table:', usersError.message);
    
    // Initialize Ballots table
    const { error: ballotsError } = await supabase.rpc('exec', {
      sql: `
        CREATE TABLE IF NOT EXISTS ballots (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          sr_numbers JSONB NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
      `
    });
    if (ballotsError) {
      console.error('❌ Error creating ballots table:', ballotsError.message);
      console.log('📋 Please create the ballots table manually in Supabase SQL Editor with:');
      console.log('CREATE TABLE ballots (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, sr_numbers JSONB NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW());');
    }
    
    // Create default admin user
    const { data: existingUser } = await supabase
      .from('users')
      .select('*')
      .eq('username', DEFAULT_USERNAME)
      .single();
    
    if (!existingUser) {
      await supabase.from('users').insert({
        username: DEFAULT_USERNAME,
        password: DEFAULT_PASSWORD
      });
      console.log('✅ Default user created: ' + DEFAULT_USERNAME);
    } else {
      console.log('✅ Default user already exists');
    }
  } catch (error) {
    console.log('⚠️  Note: Database tables may need manual creation in Supabase:', error.message);
  }
}

initializeDatabase();

app.post('/login', async (req, res) => {
  const { username, password } = req.body;

  try {
    // First check if it's the default admin
    if (username === DEFAULT_USERNAME && password === DEFAULT_PASSWORD) {
      return res.json({ success: true, role: 'admin', username });
    }

    // Then check database
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .eq('password', password)
      .single();

    if (error || !data) {
      return res.status(401).json({ success: false });
    }

    res.json({ success: true, role: getUserRole(data.username), username: data.username });
  } catch (error) {
    console.error('Login error:', error);
    res.status(401).json({ success: false });
  }
});

async function insertUser({ username, password, role }) {
  const { data, error } = await supabase
    .from('users')
    .insert({ username, password })
    .select();
  if (!error && username) setUserRole(username, role);
  return { data, error };
}

async function updateUserById(id, fields) {
  const { username, role } = fields;
  if (role && username) setUserRole(username, role);
  const { role: _r, ...dbFields } = fields;
  const { data, error } = await supabase
    .from('users')
    .update(dbFields)
    .eq('id', id)
    .select();
  return { data, error };
}

app.post('/register', async (req, res) => {
  let { username, password, role } = req.body;

  try {
    if (!username || !password) {
      return res.status(400).json({ error: 'Username and password are required' });
    }

    if (username.length < 3) {
      return res.status(400).json({ error: 'Username must be at least 3 characters' });
    }

    if (password.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters' });
    }

    // Check if user already exists
    const { data: existingUser } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .single();

    if (existingUser) {
      return res.status(400).json({ error: 'Username already exists' });
    }

    // Create new user
    const { data, error } = await insertUser({ username, password, role });

    if (error) {
      console.error('❌ Registration database error:', error.message);
      return res.status(400).json({ error: `Registration failed: ${error.message}` });
    }

    res.json({ success: true, message: 'User created successfully' });
  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.post('/reset-password', async (req, res) => {
  const { username, newPassword } = req.body;

  try {
    if (!username || !newPassword) {
      return res.status(400).json({ error: 'Username and new password are required' });
    }

    if (newPassword.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters' });
    }

    // Check if user exists
    const { data: user, error: fetchError } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .single();

    if (fetchError || !user) {
      return res.status(400).json({ error: 'User not found' });
    }

    // Update password
    const { data, error: updateError } = await supabase
      .from('users')
      .update({
        password: newPassword,
        updated_at: new Date().toISOString()
      })
      .eq('username', username)
      .select();

    if (updateError) {
      return res.status(400).json({ error: 'Password reset failed' });
    }

    res.json({ success: true, message: 'Password updated successfully' });
  } catch (error) {
    console.error('Password reset error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.get('/users', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('id, username, created_at')
      .order('username', { ascending: true });

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    const roles = loadRoles();
    res.json(data.map(u => ({ ...u, role: roles[u.username] || 'dashboard' })));
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.delete('/users/:id', async (req, res) => {
  const { id } = req.params;
  try {
    const { data: user } = await supabase
      .from('users')
      .select('username')
      .eq('id', id)
      .single();

    const { error } = await supabase
      .from('users')
      .delete()
      .eq('id', id);

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    if (user) deleteUserRole(user.username);
    res.json({ success: true, message: 'User deleted' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.put('/users/:id', async (req, res) => {
  const { id } = req.params;
  const { username, password, role } = req.body;
  try {
    const updateData = { username };
    if (password) updateData.password = password;
    if (role) updateData.role = role;

    const { data, error } = await updateUserById(id, updateData);

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'User updated', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/upload-excel', upload.single('file'), async (req, res) => {
  try {
    const workbook = XLSX.readFile(req.file.path);

    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const data = XLSX.utils.sheet_to_json(sheet);

    for (const row of data) {
      await supabase.from('votes').insert({
        sr_number: row['SR Number'] || row['sr_number'] || '',
        voter_name: row['Name'] || '',
        village: row['Village'] || '',
        mobile: row['Mobile'] || '',
        logo: row['Logo'] || row['logo'] || '',
        total_votes: row['Votes'] || 0
      });
    }

    fs.unlinkSync(req.file.path);

    res.json({ success: true, message: 'Excel Imported' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/upload-logo', upload.single('logo'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }
    const url = `/uploads/${req.file.filename}`;
    res.json({ success: true, url });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Simple JSON file store for candidate party logos
const CANDIDATE_LOGOS_FILE = './candidate_logos.json';
function loadCandidateLogos() {
  try { return JSON.parse(fs.readFileSync(CANDIDATE_LOGOS_FILE, 'utf8')); } catch { return {}; }
}
function saveCandidateLogos(data) {
  fs.writeFileSync(CANDIDATE_LOGOS_FILE, JSON.stringify(data, null, 2));
}

app.post('/candidate-logo', (req, res) => {
  const { sr_number, logo_url } = req.body;
  if (!sr_number) return res.status(400).json({ error: 'sr_number required' });
  const data = loadCandidateLogos();
  data[String(sr_number)] = logo_url || '';
  saveCandidateLogos(data);
  res.json({ success: true });
});

app.get('/candidate-logo/:sr_number', (req, res) => {
  const data = loadCandidateLogos();
  res.json({ logo_url: data[String(req.params.sr_number)] || '' });
});

app.get('/votes', async (req, res) => {
  const { data, error } = await supabase
    .from('votes')
    .select('*')
    .order('sr_number', { ascending: true });

  if (error) {
    return res.status(500).json(error);
  }

  res.json(data);
});

app.post('/votes', async (req, res) => {
  const { sr_number, voter_name, logo, village, mobile, total_votes } = req.body;

  if (!sr_number || !voter_name) {
    return res.status(400).json({ error: 'SR Number and name are required' });
  }

  try {
    const { data, error } = await supabase
      .from('votes')
      .insert([{ sr_number, voter_name, logo, village, mobile, total_votes: total_votes || 0 }])
      .select();

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate added', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.put('/votes/:id', async (req, res) => {
  const { id } = req.params;
  const { sr_number, voter_name, logo, village, mobile, total_votes } = req.body;

  if (!sr_number || !voter_name) {
    return res.status(400).json({ error: 'SR Number and name are required' });
  }

  try {
    const { data, error } = await supabase
      .from('votes')
      .update({ sr_number, voter_name, logo, village, mobile, total_votes: total_votes || 0 })
      .eq('id', id)
      .select();

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate updated', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.delete('/votes/:id', async (req, res) => {
  const { id } = req.params;

  try {
    const { error } = await supabase
      .from('votes')
      .delete()
      .eq('id', id);

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate deleted' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.get('/ballots', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('ballots')
      .select('*')
      .order('created_at', { ascending: true });

    if (error) {
      // If table doesn't exist, return empty array instead of 500
      if (error.code === 'PGRST204' || error.code === 'PGRST205' || error.message.includes('not found')) {
        return res.json([]);
      }
      return res.status(500).json(error);
    }

    // Merge entered_by from log
    const entries = loadBallotLog();
    const enriched = (data || []).map(b => ({
      ...b,
      entered_by: entries[String(b.id)]?.entered_by || null
    }));

    res.json(enriched);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.delete('/ballots/:id', async (req, res) => {
  const { id } = req.params;

  try {
    // 1. Get the ballot to know which SR numbers to decrement
    const { data: ballot, error: fetchError } = await supabase
      .from('ballots')
      .select('*')
      .eq('id', id)
      .single();

    if (fetchError || !ballot) {
      return res.status(404).json({ error: 'Ballot not found' });
    }

    // 2. Decrement votes for each SR number in the ballot
    if (ballot.sr_numbers) {
      if (Array.isArray(ballot.sr_numbers)) {
        for (const sr_number of ballot.sr_numbers) {
          const { data: member } = await supabase.from('votes').select('id, total_votes').eq('sr_number', String(sr_number)).single();
          if (member) {
            const newVoteCount = Math.max(0, (member.total_votes || 0) - 1);
            await supabase.from('votes').update({ total_votes: newVoteCount }).eq('id', member.id);
          }
        }
      } else {
        // Handle object format
        for (const [sr_number, count] of Object.entries(ballot.sr_numbers)) {
          const { data: member } = await supabase.from('votes').select('id, total_votes').eq('sr_number', String(sr_number)).single();
          if (member) {
            const newVoteCount = Math.max(0, (member.total_votes || 0) - count);
            await supabase.from('votes').update({ total_votes: newVoteCount }).eq('id', member.id);
          }
        }
      }
    }

    // 3. Delete the ballot
    const { error: deleteError } = await supabase
      .from('ballots')
      .delete()
      .eq('id', id);

    if (deleteError) {
      return res.status(500).json({ error: deleteError.message });
    }

    // Clean up entry log
    removeBallotEntry(id);

    res.json({ success: true, message: 'Ballot deleted and votes adjusted' });
  } catch (error) {
    console.error('Delete ballot error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.put('/ballots/:id', async (req, res) => {
  const { id } = req.params;
  const { sr_number, new_count } = req.body;

  try {
    const { data: ballot, error: fetchError } = await supabase.from('ballots').select('*').eq('id', id).single();
    if (fetchError || !ballot) return res.status(404).json({ error: 'Ballot not found' });

    let old_count = 0;
    if (Array.isArray(ballot.sr_numbers)) {
      old_count = ballot.sr_numbers.includes(String(sr_number)) ? 1 : 0;
    } else {
      old_count = ballot.sr_numbers[sr_number] || 0;
    }

    const diff = new_count - old_count;
    if (diff === 0) return res.json({ success: true, noChange: true });

    // Update member total
    const { data: member } = await supabase.from('votes').select('id, total_votes').eq('sr_number', String(sr_number)).single();
    if (!member) return res.status(404).json({ error: 'Candidate not found' });

    const new_total = Math.max(0, (member.total_votes || 0) + diff);
    await supabase.from('votes').update({ total_votes: new_total }).eq('id', member.id);

    // Update ballot content
    let updated_sr_numbers = ballot.sr_numbers;
    if (Array.isArray(updated_sr_numbers)) {
      // Convert to object/map for numeric support
      const obj = {};
      updated_sr_numbers.forEach(s => obj[s] = 1);
      updated_sr_numbers = obj;
    }
    updated_sr_numbers[sr_number] = new_count;

    await supabase.from('ballots').update({ sr_numbers: updated_sr_numbers }).eq('id', id);

    res.json({ success: true, new_ballot_count: new_count, new_member_total: new_total });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/by-sr/vote', async (req, res) => {
  const { sr_number, entered_by } = req.body;

  if (!sr_number) {
    return res.status(400).json({ error: 'SR Number is required' });
  }

  try {
    const { data: member, error: fetchError } = await supabase
      .from('votes')
      .select('id, total_votes')
      .eq('sr_number', String(sr_number))
      .single();

    if (fetchError || !member) {
      return res.status(404).json({ error: 'SR Number not found' });
    }

    const newVoteCount = (member.total_votes || 0) + 1;

    // Update vote count
    const { data, error: updateError } = await supabase
      .from('votes')
      .update({ total_votes: newVoteCount })
      .eq('id', member.id)
      .select();

    if (updateError) {
      return res.status(500).json({ error: updateError.message });
    }

    // Record individual ballot with entered_by tracking
    const { data: ballotData, error: ballotError } = await supabase.from('ballots').insert({ sr_numbers: [String(sr_number)] }).select();
    if (ballotError) {
      console.error('❌ Failed to record ballot:', ballotError.message);
    } else if (ballotData && ballotData[0] && entered_by) {
      setBallotEntry(ballotData[0].id, entered_by);
    }

    res.json({ success: true, message: 'Vote recorded', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/by-sr/votes', async (req, res) => {
  const { sr_numbers, entered_by } = req.body;

  if (!sr_numbers || !Array.isArray(sr_numbers) || sr_numbers.length === 0) {
    return res.status(400).json({ error: 'SR Numbers array is required' });
  }

  try {
    const results = [];
    const errors = [];
    const processedSrNumbers = [];

    for (const sr_number of sr_numbers) {
      try {
        const { data: member, error: fetchError } = await supabase
          .from('votes')
          .select('id, voter_name, total_votes')
          .eq('sr_number', String(sr_number))
          .single();

        if (fetchError || !member) {
          errors.push({ sr_number, error: 'SR Number not found' });
          continue;
        }

        const newVoteCount = (member.total_votes || 0) + 1;

        const { data, error: updateError } = await supabase
          .from('votes')
          .update({ total_votes: newVoteCount })
          .eq('id', member.id)
          .select();

        if (updateError) {
          errors.push({ sr_number, error: updateError.message });
          continue;
        }

        results.push({
          sr_number,
          success: true,
          data: data[0]
        });
        processedSrNumbers.push(String(sr_number));
      } catch (error) {
        errors.push({ sr_number, error: error.message });
      }
    }

    // Record individual ballot for multiple SR numbers with entered_by tracking
    if (processedSrNumbers.length > 0) {
      const { data: ballotData, error: ballotError } = await supabase.from('ballots').insert({ sr_numbers: processedSrNumbers }).select();
      if (ballotError) {
        console.error('❌ Failed to record multiple ballot:', ballotError.message);
      } else if (ballotData && ballotData[0] && entered_by) {
        setBallotEntry(ballotData[0].id, entered_by);
      }
    }

    const response = {
      success: true,
      message: `Processed ${results.length} votes successfully`,
      processed: results.length,
      errors: errors.length,
      results: results,
      errors: errors
    };

    if (errors.length > 0) {
      response.warning = `${errors.length} SR numbers failed to process`;
    }

    res.json(response);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/:id/vote', async (req, res) => {
  const { id } = req.params;

  try {
    // Get current vote count
    const { data: member, error: fetchError } = await supabase
      .from('votes')
      .select('total_votes')
      .eq('id', id)
      .single();

    if (fetchError) {
      return res.status(404).json({ error: 'Member not found' });
    }

    // Increment vote count
    const newVoteCount = (member.total_votes || 0) + 1;

    const { data, error: updateError } = await supabase
      .from('votes')
      .update({ total_votes: newVoteCount })
      .eq('id', id)
      .select();

    if (updateError) {
      return res.status(500).json({ error: updateError.message });
    }

    res.json({ success: true, message: 'Vote recorded', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/bulk-update', async (req, res) => {
  const { updates } = req.body;

  if (!Array.isArray(updates) || updates.length === 0) {
    return res.status(400).json({ error: 'Updates array is required' });
  }

  try {
    const updatePromises = updates.map(async (update) => {
      const { id, total_votes } = update;
      
      if (!id) {
        throw new Error('ID is required for each update');
      }
      
      const { data, error } = await supabase
        .from('votes')
        .update({ total_votes })
        .eq('id', id)
        .select();
        
      if (error) {
        throw error;
      }
      
      return data[0];
    });
    
    const results = await Promise.all(updatePromises);
    
    res.json({ 
      success: true, 
      message: 'Bulk update completed',
      updated: results.length
    });
  } catch (error) {
    console.error('Bulk update error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.originalUrl });
});

app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

app.listen(5000, () => {
  console.log('Server running on port 5000');
});
