const express = require('express');
const cors = require('cors');
const multer = require('multer');
const XLSX = require('xlsx');
const fs = require('fs');
require('dotenv').config();

const { createClient } = require('@supabase/supabase-js');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static('public'));

const supabaseUrl = process.env.SUPABASE_URL || (process.env.SUPABASE_PROJECT_ID ? `https://${process.env.SUPABASE_PROJECT_ID}.supabase.co` : null);
const supabaseKey = process.env.SUPABASE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('SUPABASE_URL or SUPABASE_PROJECT_ID and SUPABASE_KEY (or SUPABASE_SERVICE_ROLE_KEY) are required.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const upload = multer({ dest: 'uploads/' });

const DEFAULT_USERNAME = 'NEST';
const DEFAULT_PASSWORD = 'sardar123';

// Initialize users table
async function initializeUsersTable() {
  try {
    // Try to create users table if it doesn't exist
    const { error } = await supabase.rpc('exec', {
      sql: `
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          username VARCHAR(255) UNIQUE NOT NULL,
          password VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        );
      `
    });
    
    // Create default admin user if it doesn't exist
    const { data: existingUser } = await supabase
      .from('users')
      .select('*')
      .eq('username', DEFAULT_USERNAME)
      .single();
    
    if (!existingUser) {
      await supabase.from('users').insert({
        username: DEFAULT_USERNAME,
        password: DEFAULT_PASSWORD
      });
      console.log('✅ Default user created: ' + DEFAULT_USERNAME);
    }
  } catch (error) {
    console.log('⚠️  Note: Users table may need manual creation in Supabase');
  }
}

initializeUsersTable();

app.post('/login', async (req, res) => {
  const { username, password } = req.body;

  try {
    // First check if it's the default admin
    if (username === DEFAULT_USERNAME && password === DEFAULT_PASSWORD) {
      return res.json({ success: true });
    }

    // Then check database
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .eq('password', password)
      .single();

    if (error || !data) {
      return res.status(401).json({ success: false });
    }

    res.json({ success: true });
  } catch (error) {
    console.error('Login error:', error);
    res.status(401).json({ success: false });
  }
});

app.post('/register', async (req, res) => {
  const { username, password } = req.body;

  try {
    if (!username || !password) {
      return res.status(400).json({ error: 'Username and password are required' });
    }

    if (username.length < 3) {
      return res.status(400).json({ error: 'Username must be at least 3 characters' });
    }

    if (password.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters' });
    }

    // Check if user already exists
    const { data: existingUser } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .single();

    if (existingUser) {
      return res.status(400).json({ error: 'Username already exists' });
    }

    // Create new user
    const { data, error } = await supabase
      .from('users')
      .insert({
        username,
        password
      })
      .select();

    if (error) {
      return res.status(400).json({ error: 'Registration failed' });
    }

    res.json({ success: true, message: 'User created successfully' });
  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.post('/reset-password', async (req, res) => {
  const { username, newPassword } = req.body;

  try {
    if (!username || !newPassword) {
      return res.status(400).json({ error: 'Username and new password are required' });
    }

    if (newPassword.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters' });
    }

    // Check if user exists
    const { data: user, error: fetchError } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .single();

    if (fetchError || !user) {
      return res.status(400).json({ error: 'User not found' });
    }

    // Update password
    const { data, error: updateError } = await supabase
      .from('users')
      .update({
        password: newPassword,
        updated_at: new Date().toISOString()
      })
      .eq('username', username)
      .select();

    if (updateError) {
      return res.status(400).json({ error: 'Password reset failed' });
    }

    res.json({ success: true, message: 'Password updated successfully' });
  } catch (error) {
    console.error('Password reset error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.get('/users', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('id, username, created_at')
      .order('username', { ascending: true });

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json(data);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/upload-excel', upload.single('file'), async (req, res) => {
  try {
    const workbook = XLSX.readFile(req.file.path);

    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const data = XLSX.utils.sheet_to_json(sheet);

    for (const row of data) {
      await supabase.from('votes').insert({
        sr_number: row['SR Number'] || row['sr_number'] || '',
        voter_name: row['Name'] || '',
        village: row['Village'] || '',
        mobile: row['Mobile'] || '',
        logo: row['Logo'] || row['logo'] || '',
        total_votes: row['Votes'] || 0
      });
    }

    fs.unlinkSync(req.file.path);

    res.json({ success: true, message: 'Excel Imported' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.get('/votes', async (req, res) => {
  const { data, error } = await supabase
    .from('votes')
    .select('*')
    .order('sr_number', { ascending: true });

  if (error) {
    return res.status(500).json(error);
  }

  res.json(data);
});

app.post('/votes', async (req, res) => {
  const { sr_number, voter_name, logo, village, mobile, total_votes } = req.body;

  if (!sr_number || !voter_name) {
    return res.status(400).json({ error: 'SR Number and name are required' });
  }

  try {
    const { data, error } = await supabase
      .from('votes')
      .insert([{ sr_number, voter_name, logo, village, mobile, total_votes: total_votes || 0 }])
      .select();

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate added', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.put('/votes/:id', async (req, res) => {
  const { id } = req.params;
  const { sr_number, voter_name, logo, village, mobile, total_votes } = req.body;

  if (!sr_number || !voter_name) {
    return res.status(400).json({ error: 'SR Number and name are required' });
  }

  try {
    const { data, error } = await supabase
      .from('votes')
      .update({ sr_number, voter_name, logo, village, mobile, total_votes: total_votes || 0 })
      .eq('id', id)
      .select();

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate updated', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.delete('/votes/:id', async (req, res) => {
  const { id } = req.params;

  try {
    const { error } = await supabase
      .from('votes')
      .delete()
      .eq('id', id);

    if (error) {
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true, message: 'Candidate deleted' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/by-sr/vote', async (req, res) => {
  const { sr_number } = req.body;

  if (!sr_number) {
    return res.status(400).json({ error: 'SR Number is required' });
  }

  try {
    const { data: member, error: fetchError } = await supabase
      .from('votes')
      .select('id, total_votes')
      .eq('sr_number', String(sr_number))
      .single();

    if (fetchError || !member) {
      return res.status(404).json({ error: 'SR Number not found' });
    }

    const newVoteCount = (member.total_votes || 0) + 1;

    const { data, error: updateError } = await supabase
      .from('votes')
      .update({ total_votes: newVoteCount })
      .eq('id', member.id)
      .select();

    if (updateError) {
      return res.status(500).json({ error: updateError.message });
    }

    res.json({ success: true, message: 'Vote recorded', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/by-sr/votes', async (req, res) => {
  const { sr_numbers } = req.body;

  if (!sr_numbers || !Array.isArray(sr_numbers) || sr_numbers.length === 0) {
    return res.status(400).json({ error: 'SR Numbers array is required' });
  }

  try {
    const results = [];
    const errors = [];

    for (const sr_number of sr_numbers) {
      try {
        const { data: member, error: fetchError } = await supabase
          .from('votes')
          .select('id, voter_name, total_votes')
          .eq('sr_number', String(sr_number))
          .single();

        if (fetchError || !member) {
          errors.push({ sr_number, error: 'SR Number not found' });
          continue;
        }

        const newVoteCount = (member.total_votes || 0) + 1;

        const { data, error: updateError } = await supabase
          .from('votes')
          .update({ total_votes: newVoteCount })
          .eq('id', member.id)
          .select();

        if (updateError) {
          errors.push({ sr_number, error: updateError.message });
          continue;
        }

        results.push({
          sr_number,
          success: true,
          data: data[0]
        });
      } catch (error) {
        errors.push({ sr_number, error: error.message });
      }
    }

    const response = {
      success: true,
      message: `Processed ${results.length} votes successfully`,
      processed: results.length,
      errors: errors.length,
      results: results,
      errors: errors
    };

    if (errors.length > 0) {
      response.warning = `${errors.length} SR numbers failed to process`;
    }

    res.json(response);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/:id/vote', async (req, res) => {
  const { id } = req.params;

  try {
    // Get current vote count
    const { data: member, error: fetchError } = await supabase
      .from('votes')
      .select('total_votes')
      .eq('id', id)
      .single();

    if (fetchError) {
      return res.status(404).json({ error: 'Member not found' });
    }

    // Increment vote count
    const newVoteCount = (member.total_votes || 0) + 1;

    const { data, error: updateError } = await supabase
      .from('votes')
      .update({ total_votes: newVoteCount })
      .eq('id', id)
      .select();

    if (updateError) {
      return res.status(500).json({ error: updateError.message });
    }

    res.json({ success: true, message: 'Vote recorded', data: data[0] });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/votes/bulk-update', async (req, res) => {
  const { updates } = req.body;

  if (!Array.isArray(updates) || updates.length === 0) {
    return res.status(400).json({ error: 'Updates array is required' });
  }

  try {
    const updatePromises = updates.map(async (update) => {
      const { id, total_votes } = update;
      
      if (!id) {
        throw new Error('ID is required for each update');
      }
      
      const { data, error } = await supabase
        .from('votes')
        .update({ total_votes })
        .eq('id', id)
        .select();
        
      if (error) {
        throw error;
      }
      
      return data[0];
    });
    
    const results = await Promise.all(updatePromises);
    
    res.json({ 
      success: true, 
      message: 'Bulk update completed',
      updated: results.length
    });
  } catch (error) {
    console.error('Bulk update error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.originalUrl });
});

app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

app.listen(5000, () => {
  console.log('Server running on port 5000');
});
