const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = `https://${process.env.SUPABASE_PROJECT_ID}.supabase.co`;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

async function setupUsersTable() {
  console.log('🔄 Setting up users table...\n');

  try {
    // Create users table by querying a non-existent endpoint
    console.log('1️⃣  Creating users table...');
    
    // First, try to list tables to see if users exists
    const { data: tables, error: tableError } = await supabase
      .from('information_schema.tables')
      .select('*')
      .eq('table_schema', 'public')
      .eq('table_name', 'users');

    let tableExists = false;
    if (!tableError && tables && tables.length > 0) {
      tableExists = true;
    }

    if (!tableExists) {
      console.log('   ⚠️  Users table does not exist. Creating it...');
      
      // Create the table using a raw POST request via the REST API
      const headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supabaseKey}`,
        'apiKey': supabaseKey
      };

      const sql = `
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          username VARCHAR(255) UNIQUE NOT NULL,
          password VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        );
      `;

      try {
        const response = await fetch(`${supabaseUrl}/rest/v1/rpc/exec`, {
          method: 'POST',
          headers: headers,
          body: JSON.stringify({ sql })
        });

        if (response.ok) {
          console.log('   ✅ Users table created!\n');
          tableExists = true;
        } else {
          console.log('   ⚠️  Could not create table via API.\n');
        }
      } catch (fetchError) {
        console.log('   ⚠️  Could not create table. Please create manually.\n');
      }
    } else {
      console.log('   ✅ Users table already exists!\n');
    }

    // Check if default user exists
    console.log('2️⃣  Checking default admin user...');
    const { data: existingUser, error: fetchError } = await supabase
      .from('users')
      .select('*')
      .eq('username', 'NEST')
      .single();

    if (existingUser) {
      console.log('   ✅ Default user "NEST" already exists!\n');
    } else {
      console.log('   Creating default user "NEST"...');
      const { error: insertError } = await supabase
        .from('users')
        .insert({
          username: 'NEST',
          password: 'sardar123'
        });

      if (insertError) {
        console.log('   ⚠️  Could not insert default user:', insertError.message);
        console.log('   Try inserting manually:\n');
        console.log('   INSERT INTO users (username, password)');
        console.log('   VALUES (\'NEST\', \'sardar123\');\n');
      } else {
        console.log('   ✅ Default user created!\n');
      }
    }

    console.log('✨ Setup complete!\n');
    console.log('📝 Default credentials:');
    console.log('   Username: NEST');
    console.log('   Password: sardar123\n');
    console.log('🚀 You can now start the server with: npm start\n');

  } catch (error) {
    console.error('❌ Error during setup:', error.message);
    console.log('\n📖 Manual Setup Instructions:');
    console.log('1. Go to: https://app.supabase.com');
    console.log('2. Select your project: lbzacdkhfvhcswrqcbxl');
    console.log('3. Go to SQL Editor → New Query');
    console.log('4. Run this SQL:\n');
    console.log(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
      ALTER TABLE users DISABLE ROW LEVEL SECURITY;
      INSERT INTO users (username, password) VALUES ('NEST', 'sardar123') ON CONFLICT DO NOTHING;
    `);
    process.exit(1);
  }
}

setupUsersTable();
