#!/usr/bin/env node

require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL || (process.env.SUPABASE_PROJECT_ID ? `https://${process.env.SUPABASE_PROJECT_ID}.supabase.co` : null);
const supabaseKey = process.env.SUPABASE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials!');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Generate 100 members
function generateMembers() {
  const members = [];
  
  const firstNames = ['Anil', 'Rajesh', 'Vikram', 'Deepak', 'Suresh', 'Ramesh', 'Mahesh', 'Arjun', 
                     'Ajay', 'Nitin', 'Sanjay', 'Pradeep', 'Rohit', 'Ashok', 'Kiran', 'Mohan',
                     'Pankaj', 'Ravi', 'Sandeep', 'Atul', 'Ritesh', 'Harsh', 'Varun', 'Siddharth',
                     'Anish', 'Bhavesh', 'Chintan', 'Darshan', 'Eshan', 'Farhan', 'Girish', 'Harish'];
  
  const lastNames = ['Sharma', 'Patel', 'Verma', 'Singh', 'Kumar', 'Gupta', 'Yadav', 'Reddy',
                    'Khan', 'Desai', 'Chopra', 'Pandey', 'Saxena', 'Joshi', 'Nair', 'Iyer',
                    'Bhat', 'Bhatnagar', 'Dwivedi', 'Trivedi'];
  
  const villages = ['Ahmedabad', 'Vadodara', 'Rajkot', 'Surat', 'Bhavnagar', 'Jamnagar', 
                   'Junagadh', 'Porbandar', 'Morbi', 'Gondal'];
  
  for (let i = 1; i <= 100; i++) {
    const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
    const village = villages[Math.floor(Math.random() * villages.length)];
    
    members.push({
      sr_number: i,
      voter_name: `${firstName} ${lastName}`,
      village: village,
      mobile: '98' + String(Math.floor(Math.random() * 100000000)).padStart(8, '0'),
      logo: `https://ui-avatars.com/api/?name=${firstName}+${lastName}&background=random`,
      total_votes: 0
    });
  }
  
  return members;
}

async function setupDatabase() {
  try {
    console.log('🔄 Setting up database...\n');
    
    // Try to create table using SQL
    console.log('📝 Creating votes table...');
    const { error: createError } = await supabase.rpc('exec', {
      sql: `
        CREATE TABLE IF NOT EXISTS votes (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          sr_number INT UNIQUE,
          voter_name VARCHAR(255) NOT NULL,
          village VARCHAR(255),
          mobile VARCHAR(20),
          logo TEXT,
          total_votes INT DEFAULT 0,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        );
      `
    });
    
    if (createError && createError.message !== 'Unknown RPC Error') {
      // RPC might not exist, try direct insert which will fail if table doesn't exist
      console.log('⚠️  Cannot create table via RPC. Attempting direct insert...');
    }
    
    console.log('✅ Table ready!\n');
    
    console.log('🔄 Generating 100 members...');
    const members = generateMembers();
    console.log(`✅ Generated ${members.length} members\n`);
    
    console.log('📤 Inserting members into database...');
    const { data, error: insertError } = await supabase
      .from('votes')
      .insert(members)
      .select();
    
    if (insertError) {
      console.error('❌ Insert error:', insertError);
      console.error('This usually means the table needs to be created manually in Supabase.');
      console.log('\n📋 Alternative: Create table manually in Supabase SQL Editor with:');
      console.log(`
CREATE TABLE votes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sr_number INT UNIQUE,
  voter_name VARCHAR(255) NOT NULL,
  village VARCHAR(255),
  mobile VARCHAR(20),
  logo TEXT,
  total_votes INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
      `);
      process.exit(1);
    }
    
    console.log('✅ Successfully inserted members!');
    console.log(`📊 Total members added: ${data.length}\n`);
    
    // Verify
    const { count, error: countError } = await supabase
      .from('votes')
      .select('*', { count: 'exact', head: true });
    
    if (!countError) {
      console.log(`📈 Total records in database: ${count}`);
    }
    
    console.log('\n✔️ Database setup complete!');
    process.exit(0);
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

setupDatabase();
