#!/bin/bash

# This script creates the users table in Supabase for user registration and password reset

echo "🔄 Setting up users table in Supabase..."
echo ""
echo "⚠️  IMPORTANT: You must manually run this SQL in Supabase SQL Editor:"
echo ""
echo "Go to: https://app.supabase.com → Your Project → SQL Editor → New Query"
echo ""
echo "Copy and paste this SQL:"
echo ""
echo "========== SQL START =========="
cat << 'EOF'
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Disable RLS for now (can be enabled with policies later)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

-- Insert default admin user (only if it doesn't exist)
INSERT INTO users (username, password) 
VALUES ('NEST', 'sardar123')
ON CONFLICT (username) DO NOTHING;

-- Grant permissions
GRANT ALL ON users TO public;
GRANT ALL ON users TO anon;
GRANT ALL ON users TO authenticated;
GRANT ALL ON users TO service_role;
EOF
echo ""
echo "========== SQL END =========="
echo ""
echo "✅ After running the SQL, restart the server:"
echo ""
echo "   npm start"
echo ""
echo "Then test at: http://localhost:5000"
